# Generated by Django 5.0.1 on 2024-01-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
